apiVersion: v1
kind: Namespace
metadata:
  name:  api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-svc
  namespace: api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: product-svc
  template:
    metadata:
      labels:
        app: product-svc
    spec:
      containers:
      - name: api-container
        image: ttl.sh/telepresence-demo-product-svc:2h
        imagePullPolicy: Always
        ports:
        - name:  api
          port:  8080
          containerPort: 8080
          protocol: TCP
---
kind: Service
apiVersion: v1
metadata:
  name:  product-svc
  namespace: api
spec:
  selector:
    app:  product-svc
  type:  ClusterIP
  ports:
  - name: api
    port:  80
    targetPort:  8080
    containerPort: 8080