{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.product.name }}-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.product.name }}-{{ .Values.product.branch }}-{{ .Values.product.prnumber }}.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.product.branch }}-{{ .Values.product.prnumber }}-product-dev
                port:
                  number: 8080
{{- end }}

